client_max_body_size 2m;

location ^~ /_next/static/ {
  include /etc/nginx/snippets/sparky-proxy-params.conf;
  proxy_pass http://sparky_storefront;
  expires 365d;
  include /etc/nginx/snippets/sparky-security-headers.conf;
  add_header Cache-Control "public, max-age=31536000, immutable" always;
}

location / {
  include /etc/nginx/snippets/sparky-proxy-params.conf;
  proxy_pass http://sparky_storefront;
}
