# shellcheck shell=bash
# Stages: existing, medusa, storage, storefront

SERVER_HEAP_MB=${SERVER_HEAP_MB:-2048}
WORKER_HEAP_MB=${WORKER_HEAP_MB:-1536}
STOREFRONT_HEAP_MB=${STOREFRONT_HEAP_MB:-1024}
export SERVER_HEAP_MB WORKER_HEAP_MB STOREFRONT_HEAP_MB

scheme() { if [ "${ENABLE_TLS:-yes}" = yes ]; then echo https; else echo http; fi; }

# ------------------------------------------------------------------ existing
# A previous Medusa project may exist in ~/sparky-commerce. Inventory it and
# back it up. Nothing is modified or deleted.
stage_existing() {
  local found=0 d
  for d in /root/sparky-commerce /home/*/sparky-commerce; do
    [ -d "$d" ] || continue
    found=1
    info "existing project found: $d"
    local be="$d/apps/backend" ts out ver
    ts=$(date -u +%Y%m%dT%H%M%SZ)
    out="$SPARKY_BACKUP_DIR/pre-install-existing-$ts"
    install -d -m 0700 "$out"
    if [ -f "$be/package.json" ]; then
      ver=$(jq -r '.dependencies["@medusajs/medusa"] // "unknown"' "$be/package.json")
      info "  @medusajs/medusa: $ver   package manager lockfiles: $(cd "$be" && ls package-lock.json yarn.lock pnpm-lock.yaml 2>/dev/null | tr '\n' ' ')"
      echo "medusa=$ver" >"$out/inventory.txt"
    fi
    # code snapshot (without node_modules/build output); includes .env → 0600 root
    run tar --exclude=node_modules --exclude=.medusa --exclude=.next -czf "$out/project.tgz" -C "$(dirname "$d")" "$(basename "$d")"
    chmod 600 "$out/project.tgz"
    local envf url
    for envf in "$be/.env" "$d/.env"; do
      [ -f "$envf" ] || continue
      url=$(grep -E '^DATABASE_URL=' "$envf" | tail -1 | cut -d= -f2- | tr -d '"'"'" || true)
      if [ -n "$url" ]; then
        CURRENT_CMD="pg_dump existing database (url redacted)"
        if pg_dump --format=custom --no-owner --file="$out/existing-db.dump" "$url" >>"$SPARKY_LOG" 2>&1; then
          chmod 600 "$out/existing-db.dump"
          pass "  existing database dumped to $out/existing-db.dump"
        else
          warn "  could not dump the existing database (see log); continuing without modifying it"
        fi
      fi
    done
    # processes that would collide with our ports
    local p pid cmd
    for p in 3000 9000; do
      pid=$(lsof -t -iTCP:"$p" -sTCP:LISTEN 2>/dev/null | head -1 || true)
      [ -n "$pid" ] || continue
      cmd=$(tr '\0' ' ' </proc/"$pid"/cmdline | cut -c1-100)
      case "$cmd" in *"$SPARKY_HOME"*) continue ;; esac
      if [ "${EXISTING_STOP:-no}" = yes ]; then
        warn "  stopping process on port $p ($cmd) as requested (EXISTING_STOP=yes)"
        if have pm2; then pm2 stop all >>"$SPARKY_LOG" 2>&1 || true; fi
        kill "$pid" || true
      else
        die "port $p is used by the existing installation ($cmd). Stop it yourself or re-run with EXISTING_STOP=yes (a backup is in $out)."
      fi
    done
    pass "  existing installation backed up to $out (left untouched)"
  done
  [ "$found" = 1 ] || skip "no existing ~/sparky-commerce installation"
}

# -------------------------------------------------------------------- medusa
new_release() {
  local sha id
  sha=$(git -C "$REPO_DIR" rev-parse --short HEAD 2>/dev/null || echo nogit)
  local pending
  pending=$(cat "$SPARKY_STATE_DIR/pending-release" 2>/dev/null || true)
  if [ -n "$pending" ] && [ -d "$pending" ] && [[ "$pending" == *"-$sha" ]]; then
    RELEASE_DIR=$pending # resume an interrupted build of the same commit
  else
    id="$(date -u +%Y%m%d%H%M%S)-$sha"
    RELEASE_DIR="$SPARKY_RELEASES/$id"
  fi
  CURRENT_CMD="copy source to $RELEASE_DIR"
  install -d -o "$SPARKY_USER" -g "$SPARKY_USER" "$RELEASE_DIR"
  rsync -a --delete \
    --exclude node_modules --exclude .medusa --exclude .next --exclude '.env' --exclude '.env.*' \
    --exclude 'apps/backend/static' --exclude 'apps/backend/private-uploads' --exclude 'test-results' --exclude 'playwright-report' \
    --include '.env.example' \
    "$REPO_DIR/" "$RELEASE_DIR/"
  chown -R "$SPARKY_USER:$SPARKY_USER" "$RELEASE_DIR"
  echo "$RELEASE_DIR" >"$SPARKY_STATE_DIR/pending-release"
  export RELEASE_DIR
}

write_backend_env() {
  local s db_pw redis_pw
  s=$(scheme)
  db_pw=$(secret DB_PASSWORD 24)
  redis_pw=$(secret REDIS_PASSWORD 32)
  local tmp
  tmp=$(mktemp)
  {
    echo "# Generated by deploy/install.sh — do not commit. Owner root:$SPARKY_USER 0640."
    echo "NODE_ENV=production"
    echo "STORE_NAME=Sparky 3D Craft Co"
    echo "DATABASE_URL=postgres://medusa:${db_pw}@127.0.0.1:5432/medusa_db"
    echo "DB_POOL_MAX=10"
    echo "REDIS_URL=redis://:${redis_pw}@127.0.0.1:6379/0"
    echo "EVENTS_REDIS_URL=redis://:${redis_pw}@127.0.0.1:6379/1"
    echo "WE_REDIS_URL=redis://:${redis_pw}@127.0.0.1:6379/2"
    echo "LOCKING_REDIS_URL=redis://:${redis_pw}@127.0.0.1:6379/3"
    echo "CACHE_REDIS_URL=redis://:${redis_pw}@127.0.0.1:6379/4"
    echo "JWT_SECRET=$(secret JWT_SECRET 48)"
    echo "COOKIE_SECRET=$(secret COOKIE_SECRET 48)"
    echo "STORE_CORS=${s}://${STORE_DOMAIN},${s}://www.${STORE_DOMAIN}"
    echo "ADMIN_CORS=${s}://${API_DOMAIN}"
    echo "AUTH_CORS=${s}://${STORE_DOMAIN},${s}://www.${STORE_DOMAIN},${s}://${API_DOMAIN}"
    echo "MEDUSA_BACKEND_URL=${s}://${API_DOMAIN}"
    echo "STOREFRONT_URL=${s}://${STORE_DOMAIN}"
    echo "STOREFRONT_REVALIDATE_URL=http://127.0.0.1:3000/api/revalidate"
    echo "REVALIDATE_SECRET=$(secret REVALIDATE_SECRET 32)"
    echo "SPARKY_DISABLE_SYSTEM_PAYMENT=true"
    echo "MEDUSA_DISABLE_TELEMETRY=true"
    echo "PRIVATE_UPLOADS_DIR=$SPARKY_VAR/private-uploads"
    echo "FILE_PROVIDER=${FILE_PROVIDER}"
    if [ "$FILE_PROVIDER" = s3 ]; then
      echo "S3_FILE_URL=${S3_FILE_URL%/}"
      echo "S3_ENDPOINT=${S3_ENDPOINT}"
      echo "S3_REGION=${S3_REGION}"
      echo "S3_BUCKET=${S3_BUCKET}"
      echo "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}"
      echo "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}"
      echo "S3_PREFIX=media/"
      if [ "${S3_DISABLE_ACL:-yes}" = yes ]; then echo "S3_DISABLE_ACL=true"; fi
      if [ -n "${S3_PRIVATE_BUCKET:-}" ]; then echo "S3_PRIVATE_BUCKET=${S3_PRIVATE_BUCKET}"; fi
    fi
    if [ -n "${RAZORPAY_KEY_ID:-}" ]; then
      echo "RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}"
      echo "RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}"
      echo "RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET:-}"
    fi
    echo "COD_ENABLED=${COD_ENABLED:-false}"
    if [ -n "${COD_MAX_ORDER_AMOUNT:-}" ]; then echo "COD_MAX_ORDER_AMOUNT=${COD_MAX_ORDER_AMOUNT}"; fi
    if [ -n "${SMTP_HOST:-}" ]; then
      echo "SMTP_HOST=${SMTP_HOST}"
      echo "SMTP_PORT=${SMTP_PORT}"
      echo "SMTP_SECURE=${SMTP_SECURE}"
      echo "SMTP_USER=${SMTP_USER:-}"
      echo "SMTP_PASS=${SMTP_PASS:-}"
      echo "SMTP_FROM=${SMTP_FROM}"
      echo "MERCHANT_NOTIFICATION_EMAIL=${MERCHANT_NOTIFICATION_EMAIL:-}"
    fi
    if [ "$SPARKY_MODE" = production ]; then echo "SPARKY_CUTOVER_COMPLETED=${SPARKY_CUTOVER_COMPLETED:-false}"; fi
  } >"$tmp"
  if install_if_changed "$tmp" "$SPARKY_BACKEND_ENV" 0640 "root:$SPARKY_USER"; then pass "wrote $SPARKY_BACKEND_ENV (0640)"; else skip "$SPARKY_BACKEND_ENV unchanged"; fi
}

write_store_config() {
  local free="null"
  if [ -n "${SHIPPING_FREE_THRESHOLD:-}" ]; then free=$SHIPPING_FREE_THRESHOLD; fi
  local tmp
  tmp=$(mktemp)
  jq -n --arg city "$WAREHOUSE_CITY" --arg pin "$WAREHOUSE_POSTCODE" --argjson amt "$SHIPPING_STANDARD_AMOUNT" --argjson free "$free" '{
    store_name: "Sparky 3D Craft Co", currency_code: "inr", country_code: "in", prices_include_tax: true,
    sales_channel_name: "Sparky Storefront", region_name: "India", tax: { default_rate: null },
    stock_location: { name: "Sparky Warehouse", address: { city: $city, province: "Karnataka", postal_code: $pin, country_code: "IN" } },
    shipping_options: [ { code: "standard", name: "Standard Shipping", description: "", amount: $amt, free_shipping_threshold: $free } ]
  }' >"$tmp"
  install_if_changed "$tmp" "$SPARKY_STORE_CONFIG" 0640 "root:$SPARKY_USER" || true
}

medusa_exec() {
  # medusa exec with the production env, from the built server directory
  local dir=$1
  shift
  (
    load_env_file "$SPARKY_BACKEND_ENV"
    cd "$dir" && sudo -u "$SPARKY_USER" -H --preserve-env env HOME="$SPARKY_HOME" "$@"
  )
}

# Non-interactive: only SAFE link/search sync actions are executed; anything
# unsafe makes the command fail instead of prompting (review manually).
run_migrations() {
  local srv=$1
  CURRENT_CMD="medusa db:migrate --execute-safe-links --execute-safe-search --all-or-nothing"
  medusa_exec "$srv" npx medusa db:migrate --execute-safe-links --execute-safe-search --all-or-nothing </dev/null >>"$SPARKY_LOG" 2>&1
  record_migrated "$(cd "$srv/../../../.." && pwd -P)"
  pass "database migrations applied (safe link/search sync only)"
}

build_backend() {
  local be="$RELEASE_DIR/apps/backend"
  CURRENT_CMD="npm ci (backend)"
  (cd "$be" && as_sparky npm ci --no-audit --no-fund) >>"$SPARKY_LOG" 2>&1
  CURRENT_CMD="medusa build"
  (
    load_env_file "$SPARKY_BACKEND_ENV"
    cd "$be" && sudo -u "$SPARKY_USER" -H --preserve-env env HOME="$SPARKY_HOME" npx medusa build
  ) >>"$SPARKY_LOG" 2>&1
  CURRENT_CMD="npm ci --omit=dev (.medusa/server)"
  (cd "$be/.medusa/server" && as_sparky npm ci --omit=dev --no-audit --no-fund) >>"$SPARKY_LOG" 2>&1
  pass "backend built ($(jq -r '.dependencies["@medusajs/medusa"]' "$be/package.json"))"
}

activate_release() {
  local tmp="$SPARKY_HOME/.current.tmp"
  ln -sfn "$RELEASE_DIR" "$tmp"
  mv -T "$tmp" "$SPARKY_CURRENT"
  rm -f "$SPARKY_STATE_DIR/pending-release"
  pass "active release → $RELEASE_DIR"
}

install_units() {
  local u tmp
  export SPARKY_USER SPARKY_CURRENT SPARKY_BACKEND_ENV SPARKY_STOREFRONT_ENV SPARKY_VAR SPARKY_LOG_DIR
  for u in "$@"; do
    tmp=$(mktemp)
    render "$DEPLOY_DIR/systemd/$u" "$tmp"
    install_if_changed "$tmp" "/etc/systemd/system/$u" 0644 root:root || true
  done
  run systemctl daemon-reload
}

stage_medusa() {
  new_release
  write_backend_env
  write_store_config
  build_backend
  local srv="$RELEASE_DIR/apps/backend/.medusa/server"
  # safety: back up a non-empty database before running migrations
  if PGPASSWORD=$(secret DB_PASSWORD 24) psql -h 127.0.0.1 -U medusa -d medusa_db -tAc "SELECT count(*) FROM information_schema.tables WHERE table_schema='public'" | grep -qv '^0$'; then
    info "database has tables — taking a backup before migrations"
    "$DEPLOY_DIR/backup.sh" --quiet --tag pre-migrate >>"$SPARKY_LOG" 2>&1 || die "pre-migration backup failed"
    pass "pre-migration backup done"
  fi
  run_migrations "$srv"
  CURRENT_CMD="setup-store"
  local pk_tmp="$SPARKY_VAR/.publishable_key.new"
  rm -f "$pk_tmp"
  medusa_exec "$srv" env SPARKY_STORE_CONFIG="$SPARKY_STORE_CONFIG" SPARKY_PUBLISHABLE_KEY_FILE="$pk_tmp" npx medusa exec ./src/scripts/setup-store.js >>"$SPARKY_LOG" 2>&1
  [ -s "$pk_tmp" ] || die "setup-store did not produce a publishable key"
  install -m 0640 -o root -g "$SPARKY_USER" "$pk_tmp" "$SPARKY_VAR/publishable_key"
  rm -f "$pk_tmp"
  pass "store configured (region India/INR tax-inclusive, shipping, sales channel, publishable key)"
  if ! stage_done admin_user; then
    local pw
    pw=$(secret ADMIN_INITIAL_PASSWORD 16)
    CURRENT_CMD="medusa user -e $ADMIN_EMAIL -p <redacted>"
    local out rc=0
    out=$(medusa_exec "$srv" npx medusa user -e "$ADMIN_EMAIL" -p "$pw" 2>&1) || rc=$?
    printf '%s\n' "$out" | grep -v -- "$pw" >>"$SPARKY_LOG" || true
    if [ "$rc" = 0 ] && ! printf '%s' "$out" | grep -qi "error"; then
      pass "admin user $ADMIN_EMAIL created (initial password stored in $SPARKY_SECRETS)"
    elif printf '%s' "$out" | grep -qi "already exists"; then
      skip "admin user already exists"
    else
      die "could not create admin user"
    fi
    mark_done admin_user
  fi
  activate_release
  install_units sparky-medusa-server.service sparky-medusa-worker.service
  run systemctl enable sparky-medusa-server sparky-medusa-worker
  run systemctl restart sparky-medusa-server sparky-medusa-worker
  wait_http http://127.0.0.1:9000/health 90 || die "medusa server did not become healthy (journalctl -u sparky-medusa-server)"
  wait_http http://127.0.0.1:9001/health 90 || die "medusa worker did not become healthy (journalctl -u sparky-medusa-worker)"
  pass "Medusa server (127.0.0.1:9000) and worker (127.0.0.1:9001) healthy"
  local since
  since=$(systemctl show -p ActiveEnterTimestamp --value sparky-medusa-server)
  if journalctl -u sparky-medusa-server --since "$since" --no-pager 2>/dev/null | grep -q "event-bus-redis' established"; then
    pass "server: Redis event bus connected (log)"
  else
    warn "server: could not confirm the Redis event bus connection in logs"
  fi
}

# ------------------------------------------------------------------- storage
stage_storage() {
  if [ "$FILE_PROVIDER" != s3 ]; then
    warn "FILE_PROVIDER=local — product media stored on this VPS (staging only; production cutover requires S3)"
    return 0
  fi
  CURRENT_CMD="S3 round-trip test"
  (
    load_env_file "$SPARKY_BACKEND_ENV"
    cd "$SPARKY_CURRENT/apps/backend/.medusa/server" && node "$DEPLOY_DIR/scripts/s3-check.mjs"
  ) 2>&1 | tee -a "$SPARKY_LOG" | sed 's/^/        /'
  [ "${PIPESTATUS[0]}" = 0 ] || die "object storage check failed"
  pass "object storage: upload, public read, delete verified"
}

# ---------------------------------------------------------------- storefront
write_storefront_env() {
  local s tmp hosts
  s=$(scheme)
  if [ "$FILE_PROVIDER" = s3 ]; then hosts="${S3_FILE_URL%/}/"; else hosts="${s}://${API_DOMAIN}/static/"; fi
  tmp=$(mktemp)
  {
    echo "# Generated by deploy/install.sh. NEXT_PUBLIC_* are baked in at build time."
    echo "MEDUSA_BACKEND_URL=http://127.0.0.1:9000"
    echo "NEXT_PUBLIC_MEDUSA_BACKEND_URL=${s}://${API_DOMAIN}"
    echo "NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=$(cat "$SPARKY_VAR/publishable_key")"
    echo "NEXT_PUBLIC_SITE_URL=${s}://${STORE_DOMAIN}"
    echo "MEDUSA_IMAGE_HOSTS=${hosts}"
    echo "REVALIDATE_SECRET=$(secret REVALIDATE_SECRET 32)"
    echo "CATALOG_REVALIDATE_SECONDS=30"
    echo "SITE_NOINDEX=$([ "$SPARKY_MODE" = production ] && echo false || echo true)"
    echo "STORE_COUNTRY_CODE=in"
    if [ "$(scheme)" = http ]; then echo "COOKIE_INSECURE=true"; fi
    echo "NEXT_TELEMETRY_DISABLED=1"
    # TEST ONLY (object storage on a private/loopback IP); final-verification fails in production
    if [ "${IMAGES_ALLOW_LOCAL_IP:-}" = true ]; then echo "IMAGES_ALLOW_LOCAL_IP=true"; fi
  } >"$tmp"
  if install_if_changed "$tmp" "$SPARKY_STOREFRONT_ENV" 0640 "root:$SPARKY_USER"; then pass "wrote $SPARKY_STOREFRONT_ENV"; else skip "$SPARKY_STOREFRONT_ENV unchanged"; fi
}

build_storefront() {
  local sf="$SPARKY_CURRENT/apps/storefront"
  CURRENT_CMD="npm ci (storefront)"
  (cd "$sf" && as_sparky env PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm ci --no-audit --no-fund) >>"$SPARKY_LOG" 2>&1
  CURRENT_CMD="next build"
  (
    load_env_file "$SPARKY_STOREFRONT_ENV"
    cd "$sf" && sudo -u "$SPARKY_USER" -H --preserve-env env HOME="$SPARKY_HOME" NODE_ENV=production npx next build
  ) >>"$SPARKY_LOG" 2>&1
  pass "storefront built (Next.js $(jq -r '.dependencies.next' "$sf/package.json"))"
}

stage_storefront() {
  wait_http http://127.0.0.1:9000/health 30 || die "Medusa must be running to build the storefront"
  write_storefront_env
  build_storefront
  install_units sparky-storefront.service
  run systemctl enable sparky-storefront
  run systemctl restart sparky-storefront
  wait_http http://127.0.0.1:3000/robots.txt 60 || die "storefront did not start (journalctl -u sparky-storefront)"
  pass "storefront running on 127.0.0.1:3000"
}
